### ISSUE TITLE
Question:  Is it possible to use this connector with the Managed Confluent Cloud?

### ISSUE THREAD

**Issue by JasonDWilson** [awslabs/eventbridge-kafka-connector#113]
Not really a feature request,  I just have a question.  Is it possible to use this connector with the Managed Confluent Cloud?

**Comment by embano1** [comment]
Hi @JasonDWilson, no worries, questions are always welcome :)

Are you able to provide AWS IAM credentials to the service/worker where the connector will be deployed? When the connector starts it uses standard AWS SDK [mechanisms](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default) to retrieve credentials required to make AWS API calls.

**Comment by embano1** [comment]
@JasonDWilson is there anything else we can help you with here or is this issue good to close? Happy to update our docs if you have more insights how to run the connector with Confluent Cloud (since I haven't tried yet).

**Comment by embano1** [comment]
Closing for now. Let me know if we should reopen.
