### ISSUE TITLE
Support plugins/interceptors to customize event handling before sending to EventBridge

### ISSUE THREAD

**Issue by embano1** [awslabs/eventbridge-kafka-connector#125]
## What is your idea?

Support plugins/interceptors to influence the event handling behavior before sending to EventBridge.  For example #110 (side-lining large events), filtering, masking (PII), etc.

Proposal for discussion:

Add `aws.eventbridge.interceptor.classes` configuration property, an **ordered** list of fully-qualified classes implementing an `Interceptor` interface (tbd): accepts single event, returns `Optional` to implement ignore/drop/skip event behavior.

The connector would provide some out-of-the-box interceptors, e.g. for S3 side-lining (claim-check) or filtering. By default, no interceptor is used (current behavior). These out-of-the-box interceptor classes  will use `aws.eventbridge.interceptor.<class_suffix>.<property>` syntax for configuration. For custom interceptor classes, the developer (provider) is responsible for property naming and to avoid conflicts with existing properties e.g., `aws.eventbridge` and Kafka connect.

### Example

```json
{
    "name": "eventbridge-e2e",
    "config": {
        "auto.offset.reset": "earliest",
        "connector.class": "software.amazon.event.kafkaconnector.EventBridgeSinkConnector",
        "topics": "eventbridge-e2e",
        "aws.eventbridge.connector.id": "eventbridge-e2e-connector",
        "aws.eventbridge.interceptor.classes": "software.amazon.event.kafkaconnector.interceptor.s3offload,com.example.org.piimasker",
        "aws.eventbridge.interceptor.s3offload.key": "myS3EventKeyRef",
        "piimasker.replacement.character": "*",
        "aws.eventbridge.eventbus.arn": "arn:aws:events:us-east-1:000000000000:event-bus/eventbridge-e2e",
        "aws.eventbridge.region": "us-east-1",
        "aws.eventbridge.endpoint.uri": "http://localstack:4566",
        "key.converter": "org.apache.kafka.connect.storage.StringConverter",
        "value.converter": "org.apache.kafka.connect.json.JsonConverter",
        "value.converter.schemas.enable": false
    }
}
```

Implementation of this feature will not break existing users.

Related:

- https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/consumer/ConsumerInterceptor.html

## Would you be willing to make the change? 

Discussed with @agebhar1 he would be interested.

## Additional context

Batching is out of scope (since it works on multiple events) and can be exposed as a separate configuration property if needed.

**Comment by embano1** [comment]
cc/ @maschnetwork @baldawar for feedback

**Comment by embano1** [comment]
Update: reading more about Kafka's [`ConsumerInterceptor`](https://kafka.apache.org/0110/javadoc/index.html?org/apache/kafka/clients/consumer/ConsumerInterceptor.html), it seems this is exactly what we want :)

**Comment by agebhar1** [comment]
The [ConsumerInterceptor](https://kafka.apache.org/35/javadoc/org/apache/kafka/clients/consumer/ConsumerInterceptor.html) requires the key and value class because it is a generic interface. Currently the sink task retrieve the data via [SinkTask#put](https://kafka.apache.org/35/javadoc/org/apache/kafka/connect/sink/SinkTask.html#put(java.util.Collection)) as a collection of [SinkRecord](https://kafka.apache.org/35/javadoc/org/apache/kafka/connect/sink/SinkRecord.html)s. We need to check if and how Kafka handles this.

**Comment by embano1** [comment]
IIUC, `ConsumerInterceptor` hits before the `sink` is involved so this is agnostic to the `sink`.

**Comment by agebhar1** [comment]
While walking through the code/packages of Kafka Connect, I found this interface [Transformation](https://kafka.apache.org/35/javadoc/org/apache/kafka/connect/transforms/Transformation.html). The generic record type must extends [ConnectRecord](https://kafka.apache.org/35/javadoc/org/apache/kafka/connect/connector/ConnectRecord.html) which [SinkRecord](https://kafka.apache.org/35/javadoc/org/apache/kafka/connect/sink/SinkRecord.html) does. The de-serialization will be handled by Kafka Connect. 

Shipped transformers from Kafka Connect can be found [here](https://github.com/apache/kafka/tree/trunk/connect/transforms/src/main/java/org/apache/kafka/connect/transforms/).

https://docs.confluent.io/platform/current/connect/transforms/overview.html
https://www.confluent.io/blog/kafka-connect-single-message-transformation-tutorial-with-examples/

**Comment by embano1** [comment]
Are you saying instead of `interceptor` we should use `transformations`?

IMHO our use case is not really transformations but "intercepting" i.e., inspecting and potentially modifying polled records **before** they're sent to the `sink`. Transformations serve a specific need and are more scoped by design (unless you do crazy stuff with it) - seems also well understood with the community.

Do you see any blocker for us in adopting the `interceptor` approach?

**Comment by embano1** [comment]
Btw: my understanding of the event flow/chain is:

Kafka Topic -> Connect -> Interceptor(s) -> Sink

**Comment by agebhar1** [comment]
> Are you saying instead of interceptor we should use transformations?

I need to understand the interceptor in more detail. How de-/serialization works to handle different key/value types. The e2e tests have already `io.confluent.monitoring.clients.interceptor.Monitoring{Producer|Consumer}Interceptor` configured. But as far as I can see from the sources, these interceptors do not de-/serialize neither key or value. 

For mutation of the value (key) we need to de-/serialize it. Not sure if/how we should do it in a fully generic way. Kafka 

> Kafka Topic -> Connect -> Interceptor(s) -> Sink

If it work's, yes.

**Comment by embano1** [comment]
Ah, got it. SerDe is your concern, ack! See this example and to discuss whether we want to follow similar approach or build a custom solution: https://github.com/irori-ab/claim-check-interceptors

**Comment by agebhar1** [comment]
Now I need some time to experiment ...

**Comment by agebhar1** [comment]
What we totally missed is that the consumer(/producer) interceptor(s) are for the whole Kafka Connect instance. So all sinks(/sources) are affected and might be configured by admins only.

**Comment by embano1** [comment]
I think you're right, though I haven't tried the following:

1) Use `consumer.override` to influence that behavior
2) Instead of configuring `consumer.interceptor.classes` on the worker, add this to the sink

Related: you might find this KIP a good background read as well: https://cwiki.apache.org/confluence/display/KAFKA/KIP-42%3A+Add+Producer+and+Consumer+Interceptors

**Comment by agebhar1** [comment]
Thanks for the information. Will investigate into `consumer.override`.

**Comment by agebhar1** [comment]
I've been tinkering with the [consumer interceptor](https://kafka.apache.org/35/javadoc/org/apache/kafka/clients/consumer/ConsumerInterceptor.html) and `consumer.override.interceptor.classes`. It is only activated for the consumer task if it is configured.

![Bildschirmfoto vom 2023-09-20 17-22-48](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/050bd4b1-fe5f-40db-a1ef-a8a57174a52f)

But unfortunately the provided configuration is not the one for registration of the sink task:

![Bildschirmfoto vom 2023-09-20 17-22-02](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/c4b16334-e795-4891-9708-db43c0cf087a)

Instead of the sink configuration the consumer properties are used:

![Bildschirmfoto vom 2023-09-20 18-03-02](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/59df534f-8485-44a5-aa8f-bf763f29c73e)

**Comment by embano1** [comment]
Thx so much @agebhar1 for digging into it!

So IIUC, we don't have access to sink-specific properties, such as key and value converters (not good), topics (well, guess not an issue), and all the `aws.` sink task related configuration settings.

I'm still not clear how would we define additional consumer properties for the interceptor classes then? Say we want to build the S3 claim-check interceptor - how would it get consumer (interceptor) specific properties e.g., `<interceptorclass>.s3.bucket`? I thought that was possible with interceptors - but now I'm wondering because I don't see the customer `aws.` properties we use in `consumerProps`, only in `sinkConfig`.

**Comment by agebhar1** [comment]
It's my pleasure.

I will have some time next week for investigation.

**Comment by agebhar1** [comment]
After spend some time with debugging the code, I understood how the configuration for the interceptor is build. The comment on the method is also a good hint

![Bildschirmfoto vom 2023-09-24 10-41-30](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/83a5bb36-ca59-4032-b2e6-e5905b0fe701)

The method `org.apache.kafka.connect.runtime.Worker#baseConsumerConfigs` copies all properties with the prefix `consumer.override`. More precise it is `org.apache.kafka.connect.runtime.Worker#baseConsumerConfigs#baseConsumerConfigs` by the argument `ConnectorClientConfigRequest.ClientType.CONSUMER`.

If we provide the configuration with the required prefix, the interceptor for the sink task get all properties:

![Bildschirmfoto vom 2023-09-24 10-50-49](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/9917a04a-52f1-4417-9219-2b5d87840db8)

**Comment by agebhar1** [comment]
@embano1 I've tried to run the `ReplaceField` Single Message Transformer (SMT) with the e2e Kafka Connect Setup and it just works.

The configuration is received. Also additional ones:
![Kafka Connect SMT- ReplaceField - config](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/639949cd-c3b0-414b-87a9-c704db6f5e2f)

And the `apply` method is invoked:
![Kafka Connect SMT- ReplaceField - apply](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/160dbe8f-998a-4ece-a886-76c42a0df52c)

**Comment by embano1** [comment]
Thx for the write up @agebhar1 ! Closing as discussed.
