### ISSUE TITLE
`java.util.ConcurrentModificationException` in `software.amazon.event.kafkaconnector.util.StatusReporterTest.shouldContainLoggingEvent ` Test

### ISSUE THREAD

**Issue by embano1** [awslabs/eventbridge-kafka-connector#129]
## To Reproduce
Sometimes in Java `build` [runs](https://github.com/embano1/eventbridge-kafka-connector/actions/runs/6204538590/job/16846716189) () I see 

```console
Error:  software.amazon.event.kafkaconnector.util.StatusReporterTest.shouldContainLoggingEvent -- Time elapsed: 0.414 s <<< ERROR!
java.util.ConcurrentModificationException
```

Looks like a data race @agebhar1 ?

## Expected behavior
No exceptions during unit tests

## Environment:
[Details about your environment (OS, Java version, Hardware)
](https://github.com/embano1/eventbridge-kafka-connector/actions/runs/6204538590/job/16846716189)

**Comment by agebhar1** [comment]
Indeed
