### ISSUE TITLE
Test seems flaky

### ISSUE THREAD

**Issue by embano1** [awslabs/eventbridge-kafka-connector#138]
## Describe the bug

cc/ @agebhar1 

With the changes introduced in #130 there seems to be another flake which I just recognized during a failing test: https://github.com/awslabs/eventbridge-kafka-connector/actions/runs/6308998411/job/17128082050#step:4:4455

```console
Error:  Errors: 
Error:    StatusReporterTest.shouldContainLoggingEvent:56 » ConditionTimeout Assertion condition defined as a software.amazon.event.kafkaconnector.util.StatusReporterTest [Extracted: level, formattedMessage] 
Expecting actual to contain the specified subsequence but failed to find the element at subsequence index 2 in actual:
subsequence element not found in actual:
  (INFO, "Total records sent=1")
actual:
  [(INFO, "Starting status reporter"),
    (INFO, "Total records sent=0"),
    (INFO, "Total records sent=0"),
    (INFO, "Total records sent=2"),
```

## To Reproduce
Seems flaky (see test runs in the jobs above)

## Expected behavior
Tests pass

## Environment:
Details about your environment (OS, Java version, Hardware)

**Comment by agebhar1** [comment]
Okay, strange. I will check/fix it.
