### ISSUE TITLE
Add git short commit to log output

### ISSUE THREAD

**Issue by embano1** [awslabs/eventbridge-kafka-connector#192]
## What is your idea?
Out git short commit SHA as a field in every log line to improve debugging.

## Would you be willing to make the change? 
Yes.

## Additional context
n/a

**Comment by embano1** [comment]
Looks like this is harder than it should be. For reference, this is how Debezium implements it using custom MDC context properties:

- user guide: https://debezium.io/documentation/reference/stable/operations/logging.html#adding-mapped-diagnostic-contexts
- code: https://github.com/debezium/debezium/blob/main/debezium-core/src/main/java/io/debezium/util/LoggingContext.java

**Comment by embano1** [comment]
Not sure if @agebhar1 or @maschnetwork sees an easy implementation here, otherwise I'm inclined to close as "not planned".

**Comment by agebhar1** [comment]
I have an idea https://github.com/git-commit-id/git-commit-id-maven-plugin it's used by Spring Boot. You can assign me for this issue @embano1.

**Comment by agebhar1** [comment]
There are at least two options to add the git short commit SHA as a field in every log line. The first is, which is already mentioned, using the Mapped Diagnostic Context (MDC) of SLF4J. But this requires to update the logging configuration for Log4j, e.g.
```properties
log4j.appender.eventbridge=org.apache.log4j.ConsoleAppender
log4j.appender.eventbridge.layout=org.apache.log4j.PatternLayout
log4j.appender.eventbridge.layout.ConversionPattern=[%d] [%t] %p [%X{eventbridge.git.short}] %m%n
log4j.additivity.software.amazon.event.kafkaconnector=false
```
The (container) log contains the commit information if configured:
```
e2e-connect-1  | [2024-01-07 18:13:40,763] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] Returning early: 0 records received
e2e-connect-1  | [2024-01-07 18:13:50,773] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] EventBridgeSinkTask put called with 0 records: []
e2e-connect-1  | [2024-01-07 18:13:50,773] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] Returning early: 0 records received
e2e-connect-1  | [2024-01-07 18:13:51,010] [pool-4-thread-1] INFO [] Total records sent=0
e2e-connect-1  | [2024-01-07 18:14:00,777] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] EventBridgeSinkTask put called with 0 records: []
e2e-connect-1  | [2024-01-07 18:14:00,779] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] Returning early: 0 records received
e2e-connect-1  | [2024-01-07 18:14:10,779] [task-thread-eventbridge-e2e-0] TRACE [302d7c5] EventBridgeSinkTask put called with 0 records: []
```

The second option is to add the information explicit to each log line 'by hand', e.g.
```java
log.trace("[{}] Returning early: 0 records received", Git.sha());
```

Both options have there pro and cons.

Which one do you prefer @embano1?

**Comment by embano1** [comment]
Thx Andreas, as always! Yeah, those were the two options I could come up with when my initial (naive) approach (from how I'd do this in Golang*) did not work out.

However, I dislike both because:

1) It requires changes to our current logger (not a big issue, but I'd rather spend our resources on other PRs) **and** the user to set up the correct appender format (which we don't control**)
1) Adding this to every log statement is redundant **and** error-prone

\* I use `zap` (but others also have this feature), where you can define root/global `fields` which will always be added to each log statement (of course, fully configurable). Looks like our current simple logger doesn't have such a [`With(...fields)`](https://pkg.go.dev/go.uber.org/zap#Logger.With) feature. Perhaps we can chose another `slf4j` compatible logger?

\** My idea was that every user, without and customization, will immediately see the commit ID (not just the property version) of the connector (s)he is running, which helps with debugging here

**Comment by embano1** [comment]
I wouldn't mind the wrapper if it's a small change!

**Comment by agebhar1** [comment]
I found this https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/LogContext.java @embano1, it's exactly what we want.

**Comment by embano1** [comment]
Oh, so you mean we use/pass the `LogContext` and add our Git commit ID which will automatically get logged then? Or do we still require MDC? Where do we get access to the `LogContext` in the connector?

**Comment by agebhar1** [comment]
We do not require the MDC. Yes, we would create **one** (singleton) `LogContext` and instead of using SLF4Js `LoggerFactory#getLogger` we use the method from the singleton.

**Comment by embano1** [comment]
I like that!
