### ISSUE TITLE
Order of events doesn't match the order of records in a partition

### ISSUE THREAD

**Issue by consal** [awslabs/eventbridge-kafka-connector#230]
I have a single-partition topic. I want to use the EventBridge sink connector to send events to EventBridge and SQS. However, the messages in SQS seem in random order.

Steps to reproduce the behaviour:
1. Create an EventBridge Rule and set SQS or SQS FIFO as a destination.
2. Produce some records to the Kafka topic.
3. Start the connector.
4. Receive a message from SQS.
5. Records are not in order.

## Expected behaviour
Events are processed in the same order as in a Kafka topic. They are ordered by offset.

## Additional context
Is it by EventBridge design, or can the connector be tweaked to support ordering?

**Comment by embano1** [comment]
Thx @consal for reaching out! I'm assuming you're using SQS FIFO queues? Can you elaborate on why you need strict ordering for your particular use case? I'm just curious, not saying you don't need it ;) (see comment below)

Your understanding is correct: today EventBridge Event Buses do not maintain order. If you have strict ordering requirements we generally propose two options in EventBridge:

- Use [EventBridge Pipes](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes.html) if it suits your requirements
- Implement a custom re-sequencer between [event bus] - [re-sequencer] - [your target] e.g., using Lambda with a state store
- Handle out-of-order events in the consumer*

\* To be honest with you, IMHO this is the only way to deal with this issue in general. For example, there are various situations which can lead to events for the same record `key` in Kafka partitions to arrive out of order e.g., not using transactional consumer with session handling, application concurrency bugs in the producer, producer reads from external source and duplicates events leading to out of order, etc. Following general code design and Domain Driven Design practices, the consumer should be prepared for these situations (incl. duplicated events) and handle those, which by the way will also increase overall throughput in your system. However, I do understand that sometimes it is not possible to defer that logic to the consumer.

**Comment by consal** [comment]
In a Kafka topic, I have events in the exact order as they happened in the source system. I'm migrating an app to use an SQS queue instead of Kafka, and I need events in the same order as in the Kafka topic.

Now that I understand that the EventBridge connector doesn't support that, I'll look into alternative solutions. Unfortunately, EventBridge pipes don't support Kafka as a source in my region.

**Comment by consal** [comment]
It's Zurich. Thank you for the explanation 😊 Please let me know if you have any updates on the feature's availability.

**Comment by embano1** [comment]
Passed to product team, thank you! Closing this for now.

**Comment by consal** [comment]
Thank you. Is there any timeline for introducing it in Zurich?

**Comment by embano1** [comment]
Can't comment on this publicly here. Feel free to reach out to the AWS support team which will get you in touch with the service team.
