### ISSUE TITLE
Supporting custom credential provider

### ISSUE THREAD

**Issue by ryancuk** [awslabs/eventbridge-kafka-connector#366]
Enable custom credential provider support in the connector so that customers can implement their own provider that will be able support their specific security need.

when customer provides their own credential provider through connector configuration, the plugin in should use the custom provider  to get the AWS credentials and when credential is expired, it should refresh the credential using the provider.

**Comment by embano1** [comment]
Thank you @ryancuk ! Will discuss with @agebhar1 on Wednesday, shouldn't be too much of effort on our side (basically designing the configuration and API).

**Comment by agebhar1** [comment]
Hi @ryancuk, I discussed the topic today with @embano1. The idea is to provide an interface e.g.:

```java
@FunctionalInterface
interface EventBridgeCredentialsProvider {
    AwsCredentialsProvider getCredentialsProvider(EventBridgeSinkConfig config);
}
```
with the configuration (from the examples, other attributes skipped for simplicity):
```json
{
    "name": "eventbridge-e2e",
    "config": {
        "aws.eventbridge.auth.credentials_provider.class": "com.example.MyCredntialProvider"
    }
}
```
Data from the JSON connector configuration (`$.config.*`) can be accessed via the provided `EventBridgeSinkConfig config`. It extends `org.apache.kafka.common.config.AbstractConfig`.

If no class is provided, the current (default) implementation will be used.

Let us know, if this will work for you. If so, I will implement the feature.

**Comment by ryancuk** [comment]
hi @agebhar1 / @embano1 ,

Thanks for proposing your concept. I'm curious as to why we should develop a new interface instead of utilizing the existing one in the AWS SDK, specifically the [AwsCredentialsProvider](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProvider.java).

Here's my perspective: the creation of a new interface, I presume within this specific connector project, may cause a tighter coupling between the client code and the connector. In our scenario, our client code is a generic library that supplies customized credentials providers for diverse connectors (for instance, Confluent connectors, AWS connectors, and others). It is designed with the aim to prevent dependence on connector libraries.

**Comment by agebhar1** [comment]
Hi @ryancuk,

If I understand you correctly, you would go for a configuration for classes which implements [AwsCredentialsProvider](https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProvider.java) rather than the mentioned factory interface? Then the class must have a no-args contstructor to create an object.

```java
package com.example;

class AwsCredentialsProviderImpl implements AwsCredentialsProvider {
   public AwsCredentialsProviderImpl() {
   // ...
   }
}
```

```json
{
    "name": "eventbridge-e2e",
    "config": {
        "aws.eventbridge.auth.credentials_provider.class": "com.example.AwsCredentialsProviderImpl"
    }
}
```

@embano1 I think we can support both with the same configuration syntax. Classes which either implements `AwsCredentialsProvider` or the mentioned `EventBridgeCredentialsProvider`. After the class is loaded we can check by reflection which interface is implemented.

**Comment by ryancuk** [comment]
hi @agebhar1,

I see your point. One possible solution would require the external provider to implement two interfaces:

1. org.apache.kafka.common.Configurable
    This would be for passing the configuration from the connector to the credentials provider.
2. software.amazon.awssdk.auth.credentials.AwsCredentialsProvider
    This would handle the logic for retrieving the credentials.

This way, if an external credential provider implementation is provided, the connector would first pass the configuration and then resolve the credentials. I hope this explanation is clear.

```
class AwsCredentialsProviderImpl implements Configurable, AwsCredentialsProvider {
   public AwsCredentialsProviderImpl() {
   // ...
   }

    @Override
    public AwsCredentials resolveCredentials() {
    //  specific logic to get the credentials
    }
    
    // ...
    
    @Override
    public void configure(Map<String, ?> map) {
    // connector configuration is injected through map
    // client code to get whatever is required for setting up the 
    }
}

```

```
package org.apache.kafka.common;
import java.util.Map;

public interface Configurable {
    void configure(Map<String, ?> var1);
}

```

**Comment by agebhar1** [comment]
Hi @ryancuk,

I forgot Kafkas `Configurable` interface. That's a great suggestion from my point of view. The configured class from
```json
{
    "name": "eventbridge-e2e",
    "config": {
        "aws.eventbridge.auth.credentials_provider.class": "com.example.AwsCredentialsProviderImpl"
    }
}
```
requires to implement `software.amazon.awssdk.auth.credentials.AwsCredentialsProvider` and have a non-arg constructor. If the class implements `org.apache.kafka.common.Configurable` then `configure(Map<String, ?> map)` will be called after the the instance was created.

```java
var clazz = Class.forName("software.amazon.event.kafkaconnector.AwsCredentialsProviderImpl");
if (!AwsCredentialsProvider.class.isAssignableFrom(clazz)) {
    throw new RuntimeException("Class " + clazz + " does not implement AwsCredentialsProvider");
}

var ctor = clazz.getDeclaredConstructor();
var obj = ctor.newInstance();
if (Configurable.class.isAssignableFrom(clazz)) {
    ((Configurable) obj).configure(configs);
}
```

**Comment by embano1** [comment]
SGTM! And the `Configurable` interface approach is much more aligned with developing connectors on Kafka. We should have done the same with [`DetailTypeMapper`](https://github.com/awslabs/eventbridge-kafka-connector/blob/main/src/main/java/software/amazon/event/kafkaconnector/mapping/DetailTypeMapper.java). 

@agebhar1 any drawbacks of requiring a non-arg constructor?
