### ISSUE TITLE
Expose JMX Metrics

### ISSUE THREAD

**Issue by embano1** [awslabs/eventbridge-kafka-connector#95]
## What is your idea?

https://docs.confluent.io/platform/current/connect/monitoring.html#use-jmx-to-monitor-kconnect

## Would you be willing to make the change? 

Yes

## Additional context

Add any other context (such as images, docs, posts) about the idea here.

**Comment by agebhar1** [comment]
Exactly, the [mentioned metrics](https://docs.confluent.io/platform/current/connect/monitoring.html#use-jmx-to-monitor-kconnect) are present out of the box. Here is a screenshot of JConsole connected to Kafka Connect

![grafik](https://github.com/awslabs/eventbridge-kafka-connector/assets/2443866/dcb62335-0011-4cf6-9d37-799abfc1bcd7)

The e2e docker compose file requires the environment variables:
```
      - KAFKA_JMX_PORT: 9102
      - KAFKA_JMX_HOSTNAME: localhost
```
and the port (e.g. 9102) to be exposed for the `connect` service.
